Add base functional
als6k/repl_app pull request #1
Opened 2020-10-05 12:46 UTC by als6k

2020-10-07 13:48 UTC, aya-soft requested changes

2020-10-07 13:48 UTC, aya-soft commented on app.rb
> +require_relative 'commander.rb'
Мы не пишем тут расширения, они могут быть разные .rb, .so и т.д.

2020-10-07 13:48 UTC, aya-soft commented on app.rb
> +    users_choice = ''
используй @ переменную, ее не надо объявлять и она изначально nil, даде если нигде не встречалась в коде до этого

2020-10-07 13:48 UTC, aya-soft commented on app.rb
> +      break if users_choice == 'quit' || users_choice == 'q'
вопрос на засыпку :) А как это превратить в обычную команду?

2020-10-07 13:48 UTC, aya-soft commented on app.rb
> +      users_choice = commander.set_command
users_choice слишком общее имя оно не отражает, что там будет, а это важно. command_name -  лучше IMHO

2020-10-07 13:48 UTC, aya-soft commented on commander.rb
> +require_relative 'registry.rb'
тоже самое  .rb мы нигде не ставим в  reqiore'ах

2020-10-07 13:48 UTC, aya-soft commented on commander.rb
> +  def set_command(message='What would you choose?')
приглашение лучше обычное ">"

2020-10-07 13:48 UTC, aya-soft commented on commander.rb
> +      registry.run_command('about')
зачем столько повторов? вызывается же одинаково? нам не нужен case тут от слова совсем ;)

2020-10-08 09:40 UTC, als6k commented on registry.rb
> +  def commands_list
Но как тогда назвать внутренний хеш, для него commands тоже было идеально?

2020-10-08 09:49 UTC, aya-soft commented on registry.rb
> +  def commands_list
Внешний интерфейс важнее ИМХО, внутренний ты пишешь и тебе понятно, а внешним будет пользоваться кто-то другой - должно быть очевидно.

2020-10-08 09:52 UTC, aya-soft commented on registry.rb
> +  def commands_list
можно `registered_commands` назвать внутренний

2020-10-08 09:52 UTC, als6k commented on commands/about.rb
> +  def initialize(*)
Если убрать конструктор из классов команд, то ругается, что мы передаем аргумент в 7 строке registry класса. Но нам для help-а нужен аргумент, а для остальных команд нет. Как тогда лучше сделать?

2020-10-08 09:56 UTC, aya-soft commented on commands/about.rb
> +  def initialize(*)
так вот как раз надо в initialize Command передавать registry и там же хранить, а остальные классы команд наследуются от него и получают эту функциональность от него

2020-10-09 09:17 UTC, aya-soft requested changes

2020-10-09 13:29 UTC, aya-soft requested changes

2020-10-09 13:29 UTC, aya-soft commented on registry.rb
> +    commands.keys.sort
огонь 🔥

2020-10-09 13:29 UTC, aya-soft commented on registry.rb
> +    command.call if command
уже не нужна эта проверка ;)

2020-10-09 13:29 UTC, aya-soft commented on commander.rb
> +class Commander
А вот теперь отчетливо видно, что класс Commander нам нафиг не нужен, все его обязанности App может взять на себя!!!

2020-10-09 13:50 UTC, aya-soft requested changes

2020-10-09 13:50 UTC, aya-soft commented on app.rb
> +  def set_command(message='>')
предлагаю этот метод удалить, а код перенести в метод run

2020-10-09 13:50 UTC, aya-soft commented on app.rb
> +  attr_reader :registry
а точно нам нужен публичный ридер?

2020-10-09 13:50 UTC, aya-soft commented on app.rb
> +    registry.register_command('about', Commands::About)
а давай регистрацию команд вынесем а отдельный метод, всё-таки initialize у нас для инициализации

2020-10-09 13:50 UTC, aya-soft commented on command.rb
> +  def initialize(registry_object)
а зачем нам путаница с разными именами, предлагаю оставить registry, и сделать ридер закрытым

2020-10-09 13:50 UTC, aya-soft commented on commands/about.rb
> +  class About < Command
а давай переименуем Command класс в Base, так мы избежим масла масляного

2020-10-09 13:50 UTC, aya-soft commented on commands/about.rb
> +  class About < Command
Commands::Command не очень, а вот Commands::Base вполне ;)

2020-10-09 13:50 UTC, aya-soft commented on registry.rb
> +    command_by(name).call
Love it 😍

2020-10-09 14:19 UTC, aya-soft requested changes

2020-10-09 14:19 UTC, aya-soft commented on base.rb
> +class Base
модуль Commands потерялся ;)

2020-10-09 14:19 UTC, aya-soft commented on app.rb
> +      puts '>'
Эта галочка называется prompt, она всегда постоянная.
На какую мысль это нас наводит???

2020-10-09 14:19 UTC, aya-soft commented on app.rb
> +      puts '>'
И мы хотим, чтобы пользователь на одной строчке с > команду набирал, как сделать?

2020-10-09 15:29 UTC, aya-soft requested changes

2020-10-09 15:29 UTC, aya-soft commented on app.rb
> +      @command_name = gets.chomp
а зачем нам @command_name теперь?

2020-10-09 16:15 UTC, aya-soft requested changes

2020-10-09 16:15 UTC, aya-soft commented on app.rb
> +require_relative './commands/missing'
это лишнее, данный файл не использует /commands/missing

2020-10-09 16:15 UTC, aya-soft commented on commands/help.rb
> +      registry.command_names.each { |command| puts command }
а попробуй сделать: `puts registry.command_names` вроде одно и то же?

2020-10-09 16:15 UTC, aya-soft commented on registry.rb
> +    @commands = Hash.new(Commands::Missing.new(self))
а вот тут нужен require, так как ты ссылаешься на Commands::Missing

2020-10-13 07:08 UTC, aya-soft approved these changes

2020-10-13 07:08 UTC, merged